disableStartupPopups: true

gui:
  commitHashLength: 5
  expandedSidePanelWeight: 5
  expandFocusedSidePanel: true
  language: en
  mouseEvents: false
  scrollOffMargin: 4
  shortTimeFormat: "15:04"
  showBottomLine: false
  showCommandLog: false
  showListFooter: false
  showPanelJumps: false
  showRandomTip: false
  showRootItemInFileTree: false
  statusPanelView: allBranchesLog
  timeFormat: "2006-01-02 15:04:05"

  authorColors:
    "*": "#D0D0D0"

  theme:
    selectedLineBgColor:
      - "#314F79"

    activeBorderColor:
      - blue

git:
  autoFetch: false
  autoRefresh: false
  branchLogCmd: git l {{branchName}} --

  allBranchesLogCmds:
    - git l

  paging:
    externalDiffCommand: difft --color=always
    useExternalDiffGitConfig: true

update:
  method: never
